// user
export const SIGN_UP_BEGIN = 'SIGN_UP_BEGIN';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';

// Books
export const FETCH_BOOKS_BEGIN = 'FETCH_BOOKS_BEGIN';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const ADD_NEW_BOOK_BEGIN = 'ADD_NEW_BOOK_BEGIN';
export const ADD_NEW_BOOK_SUCCESS = 'ADD_NEW_BOOK_SUCCESS';
export const ADD_NEW_BOOK_FAILURE = 'ADD_NEW_BOOK_FAILURE';
export const UPDATE_BOOK_BEGIN = 'UPDATE_BOOK_BEGIN';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const DELETE_BOOK_BEGIN = 'DELETE_BOOK_BEGIN';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const UPDATE_QUERY = 'UPDATE_QUERY';


// Metadata
export const FETCH_PUBLISHERS_BEGIN = 'FETCH_PUBLISHERS_BEGIN';
export const FETCH_PUBLISHERS_SUCCESS = 'FETCH_PUBLISHERS_SUCCESS';
export const FETCH_PUBLISHERS_FAILURE = 'FETCH_PUBLISHERS_FAILURE';

export const FETCH_AUTHORS_BEGIN = 'FETCH_AUTHORS_BEGIN';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';
